# 서버 설정
server:
  port: 8081  
  servlet:
    register-default-servlet: true
    session:
      timeout: 600
      cookie:
        http-only: true
        #max-age: 43200m    # 60m * 24h * 30d
        #name: SID
        #secure: true
        
# 스프링 설정  
spring:
  profiles:
    active: loc
  thymeleaf: 
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false

# 로그 설정
logging:
  config: classpath:logback-spring-dev.xml
  file:
    path: .

url:
  practice-api: http://localhost:8091