# 서버 설정
server:
  port: 8081  
  servlet:
    register-default-servlet: true
    
# 스프링 설정  
spring:
  profiles:
    active: loc
  thymeleaf: 
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false

# 로그 설정
logging:
  config: classpath:logback-spring-dev.xml
  file:
    path: .

url:
  practice-api: http://localhost:8091